### ISSUE TITLE
Package name conflicts

### ISSUE THREAD

**Issue by MichaelObi** [unicodeveloper/laravel-notification-channel-jusibe#1]
Hey, 
It's confusing seeing this package here and then the other instance in @laravel-notification-channels mostly because the ReadMes are different. I noticed this version has issues with minimum-stability too.

**Comment by unicodeveloper** [comment]
You should use th one in @laravel-notification-channels

**Comment by MichaelObi** [comment]
I think there should be something that points to that in the ReadMe. And the composer command there should change then.

**Comment by unicodeveloper** [comment]
So I used this one to Develop it, then I moved it over to Laravel
notifications channel. I will update the readme to signify that.

Composer command should change? Why?

**Comment by unicodeveloper** [comment]
This is the working version. https://github.com/laravel-notification-channels/jusibe . I have highlighted that in the readme
